
import java.util.Iterator;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author PC
 */
public class company_panel extends javax.swing.JFrame {

    /**
     * Creates new form admin_giris_paneli
     */
    public company_panel() {
        initComponents();
     ReservationSystem reSystem=new ReservationSystem();
    vehicleTable = new javax.swing.JTable();
    vehicleTable.setModel(new CompanyVehicleTableForm(getVehicleList(reSystem)));
    jScrollPane1.setViewportView(vehicleTable);
    
    
    personelTable = new javax.swing.JTable();
    personelTable.setModel(new CompanyPersonelTableForm(getPersonelList(reSystem)));
    jScrollPane2.setViewportView(personelTable);
    
    
    }
    
    private List<Vehicle>getVehicleList(ReservationSystem reservationSystem){
        
        Iterator<Vehicle> iterator = reservationSystem.getVehicleList().iterator();
        while (iterator.hasNext()) {
            Vehicle vehicle = iterator.next();

            // Silme koşulunu burada belirtin (örneğin, "Car" olanları silme)
            if (!vehicle.getCompanyName().equals(company_login_panel.loginCompanyName)) {
                iterator.remove(); // Iterator üzerinden silme işlemi
            }
        }
        return reservationSystem.getVehicleList();
    }
    
        private List<Personel>getPersonelList(ReservationSystem reservationSystem){
        
        Iterator<Personel> iterator = reservationSystem.getPersonelList().iterator();
        while (iterator.hasNext()) {
            Personel personel = iterator.next();

            // Silme koşulunu burada belirtin (örneğin, "Car" olanları silme)
            if (!personel.getCompanyName().equals(company_login_panel.loginCompanyName)) {
                iterator.remove(); // Iterator üzerinden silme işlemi
            }
        }
        return reservationSystem.getPersonelList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        vehicleTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        newVehicleNoLabel = new javax.swing.JLabel();
        newVehicleNoInputText = new javax.swing.JTextField();
        newVehicleVoyageNumberInputText = new javax.swing.JTextField();
        AddVehicleBtn = new javax.swing.JButton();
        deleteVehicleBtn = new javax.swing.JButton();
        nevVoyageNumberLabel = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        newCountOfSeatInputText = new javax.swing.JTextField();
        newCountOfSeatLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        personelTable = new javax.swing.JTable();
        newFuelTypeInputText = new javax.swing.JTextField();
        newFuelTypeInputLabel = new javax.swing.JLabel();
        newKmUcretiInputText = new javax.swing.JTextField();
        newKmUcretiInputLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vehicleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(vehicleTable);

        newVehicleNoLabel.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        newVehicleNoLabel.setText("Araç No:");

        newVehicleNoInputText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newVehicleNoInputTextActionPerformed(evt);
            }
        });

        newVehicleVoyageNumberInputText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newVehicleVoyageNumberInputTextActionPerformed(evt);
            }
        });

        AddVehicleBtn.setBackground(new java.awt.Color(102, 255, 102));
        AddVehicleBtn.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        AddVehicleBtn.setForeground(new java.awt.Color(255, 255, 255));
        AddVehicleBtn.setText("Ekle");
        AddVehicleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddVehicleBtnActionPerformed(evt);
            }
        });

        deleteVehicleBtn.setBackground(new java.awt.Color(255, 51, 51));
        deleteVehicleBtn.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        deleteVehicleBtn.setText("Sil");
        deleteVehicleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteVehicleBtnActionPerformed(evt);
            }
        });

        nevVoyageNumberLabel.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        nevVoyageNumberLabel.setText("Sefer No :");

        jButton5.setBackground(new java.awt.Color(153, 255, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jButton5.setText("Kar Hesabı");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        newCountOfSeatInputText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCountOfSeatInputTextActionPerformed(evt);
            }
        });

        newCountOfSeatLabel.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        newCountOfSeatLabel.setText("Koltuk Sayısı");

        personelTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(personelTable);

        newFuelTypeInputText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFuelTypeInputTextActionPerformed(evt);
            }
        });

        newFuelTypeInputLabel.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        newFuelTypeInputLabel.setText("Yakıt Türü");

        newKmUcretiInputText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newKmUcretiInputTextActionPerformed(evt);
            }
        });

        newKmUcretiInputLabel.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        newKmUcretiInputLabel.setText("Kilometre Ücreti(tl)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newVehicleNoLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nevVoyageNumberLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newCountOfSeatLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newFuelTypeInputLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newKmUcretiInputLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newCountOfSeatInputText, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newVehicleVoyageNumberInputText, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newVehicleNoInputText, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newFuelTypeInputText, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newKmUcretiInputText, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
            .addGroup(layout.createSequentialGroup()
                .addGap(361, 361, 361)
                .addComponent(AddVehicleBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteVehicleBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newVehicleNoInputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newVehicleNoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nevVoyageNumberLabel)
                    .addComponent(newVehicleVoyageNumberInputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newCountOfSeatLabel)
                    .addComponent(newCountOfSeatInputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newFuelTypeInputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newFuelTypeInputLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newKmUcretiInputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newKmUcretiInputLabel))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddVehicleBtn)
                    .addComponent(deleteVehicleBtn))
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 91, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newVehicleNoInputTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newVehicleNoInputTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newVehicleNoInputTextActionPerformed

    private void newVehicleVoyageNumberInputTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newVehicleVoyageNumberInputTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newVehicleVoyageNumberInputTextActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void AddVehicleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddVehicleBtnActionPerformed
      
        ReservationSystem reSystem=new ReservationSystem();
        CompanyVehicleTableForm model= (CompanyVehicleTableForm) vehicleTable.getModel();
       
        Vehicle vehicle = new Bus(company_login_panel.loginCompanyName,newVehicleNoInputText.getText(),Integer.parseInt(newCountOfSeatInputText.getText()),newVehicleVoyageNumberInputText.getText(),newFuelTypeInputText.getText(),Integer.parseInt(newKmUcretiInputText.getText()));
        reSystem.getVehicleList().add(vehicle);
        vehicleTable.setModel(new CompanyVehicleTableForm(reSystem.getVehicleList()));
        jScrollPane1.setViewportView(vehicleTable);
        model.addTableModelListener(vehicleTable);
        
        
    }                                                

    private void deleteExistCompanyBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                      
       

        
        
    }//GEN-LAST:event_AddVehicleBtnActionPerformed

    private void deleteVehicleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteVehicleBtnActionPerformed
        ReservationSystem reSystem=new ReservationSystem();
        CompanyVehicleTableForm model= (CompanyVehicleTableForm) vehicleTable.getModel();
       
        //Company company = new Company(newCompanyName.getText(), newCompanyPassword.getText(), newCompanyHizmetBedeli.getText());
        //reSystem.getCompanyList().add(company);
        for(Vehicle vehicle:reSystem.getVehicleList()){
            if(vehicle.getVehicleNo().equals(newVehicleNoInputText.getText())){
                reSystem.getVehicleList().remove(vehicle);
                break;
            }
        }
        vehicleTable.setModel(new CompanyVehicleTableForm(reSystem.getVehicleList()));
        jScrollPane1.setViewportView(vehicleTable);
        model.addTableModelListener(vehicleTable); 
    }//GEN-LAST:event_deleteVehicleBtnActionPerformed

    private void newCountOfSeatInputTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCountOfSeatInputTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newCountOfSeatInputTextActionPerformed

    private void newFuelTypeInputTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFuelTypeInputTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newFuelTypeInputTextActionPerformed

    private void newKmUcretiInputTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newKmUcretiInputTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newKmUcretiInputTextActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new company_panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddVehicleBtn;
    private javax.swing.JButton deleteVehicleBtn;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel nevVoyageNumberLabel;
    private javax.swing.JTextField newCountOfSeatInputText;
    private javax.swing.JLabel newCountOfSeatLabel;
    private javax.swing.JLabel newFuelTypeInputLabel;
    private javax.swing.JTextField newFuelTypeInputText;
    private javax.swing.JLabel newKmUcretiInputLabel;
    private javax.swing.JTextField newKmUcretiInputText;
    private javax.swing.JTextField newVehicleNoInputText;
    private javax.swing.JLabel newVehicleNoLabel;
    private javax.swing.JTextField newVehicleVoyageNumberInputText;
    private javax.swing.JTable personelTable;
    private javax.swing.JTable vehicleTable;
    // End of variables declaration//GEN-END:variables
}
