
import java.awt.Component;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author PC
 */
public class company_login_panel extends javax.swing.JFrame {
    
    public static String loginCompanyName;

    /**
     * Creates new form firma_paneli
     */
    public company_login_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        companyLoginBtn = new javax.swing.JButton();
        companyUserNameLabel = new javax.swing.JLabel();
        companyUserNameInputText = new javax.swing.JTextField();
        companyPasswordLabel = new javax.swing.JLabel();
        companyPasswordInputText = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        companyLoginBtn.setBackground(new java.awt.Color(102, 255, 102));
        companyLoginBtn.setText("Giris Yap");
        companyLoginBtn.setActionCommand("Giris ");
        companyLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyLoginBtnActionPerformed(evt);
            }
        });

        companyUserNameLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        companyUserNameLabel.setForeground(new java.awt.Color(51, 0, 255));
        companyUserNameLabel.setText("Kullanıcı Adı :");

        companyUserNameInputText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyUserNameInputTextActionPerformed(evt);
            }
        });

        companyPasswordLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        companyPasswordLabel.setForeground(new java.awt.Color(0, 0, 204));
        companyPasswordLabel.setText("Şifre :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(companyUserNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(companyUserNameInputText, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(companyPasswordLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(companyLoginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(companyPasswordInputText, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(companyUserNameInputText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(companyUserNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(companyPasswordInputText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(companyPasswordLabel))
                .addGap(18, 18, 18)
                .addComponent(companyLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void companyLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyLoginBtnActionPerformed
       
       ReservationSystem reservationSystem=new ReservationSystem();
        String username=companyUserNameInputText.getText();
        String password=companyPasswordInputText.getText();
        loginCompanyName=username;
        Boolean isLogin=false;
        for(Company company:reservationSystem.getCompanyList()){
            if(company.getUsername().equals(username)&&company.getPassword().equals(password)){
                company_panel a3=new company_panel();
                a3.setVisible(true);
                isLogin=true;
                break;
            }
        }
        if(!isLogin){
           Component companyLoginBtn = null;
            JOptionPane.showMessageDialog(companyLoginBtn,
                "Username or Password Incorrect");
        }

    }//GEN-LAST:event_companyLoginBtnActionPerformed

    private void companyUserNameInputTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyUserNameInputTextActionPerformed

    }//GEN-LAST:event_companyUserNameInputTextActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_login_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_login_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_login_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_login_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new company_login_panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton companyLoginBtn;
    private javax.swing.JPasswordField companyPasswordInputText;
    private javax.swing.JLabel companyPasswordLabel;
    private javax.swing.JTextField companyUserNameInputText;
    private javax.swing.JLabel companyUserNameLabel;
    // End of variables declaration//GEN-END:variables
}
